version: "3.8"

services:
  shopping-postgresql:
    container_name: shopping-postgres
    image: felipewind/shopping-postgres:13.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
        - 5432:5432
    networks:
      - shopping-net

  shopping-quarkus:
    container_name: shopping-quarkus
    image: felipewind/shopping-quarkus:1.0
    ports:
      - 8080:8080
    networks:
      - shopping-net
    depends_on:
      - shopping-postgresql
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://shopping-postgresql:5432/postgres?currentSchema=shop
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
    
  shopping-angular:
    container_name: shopping-angular
    image: felipewind/shopping-angular:1.0
    ports:
      - 80:80
    networks:
      - shopping-net
    depends_on:      
      - shopping-quarkus
    environment:      
      - API_URL=http://localhost:8080

networks:
  shopping-net:
    driver: bridge
